version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mage
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "6789:6789"
    command: mage start --host 0.0.0.0

volumes:
  postgres_data:
